/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_lwjgl_WindowsTouchImplementation */

#ifndef _Included_org_lwjgl_WindowsTouchImplementation
#define _Included_org_lwjgl_WindowsTouchImplementation
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_lwjgl_WindowsTouchImplementation
	 * Method:    nRegisterTouchWindow
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_org_lwjgl_WindowsTouchImplementation_nRegisterTouchWindow
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     org_lwjgl_WindowsTouchImplementation
	 * Method:    nGetTouches
	 * Signature: (JJJ)[Lorg/lwjgl/input/TOUCHINPUT;
	 */
	JNIEXPORT jobjectArray JNICALL Java_org_lwjgl_WindowsTouchImplementation_nGetTouches
	(JNIEnv*, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
